@echo off

:: Text Color
set "TEXT_BLACK=[30m"
set "TEXT_RED=[31m"
set "TEXT_GREEN=[32m"
set "TEXT_YELLOW=[33m"
set "TEXT_BLUE=[34m"
set "TEXT_MAGENTA=[35m"
set "TEXT_CYAN=[36m"
set "TEXT_WHITE=[37m"

:: Background Color
set "BACKGROUND_BLACK=[40m"
set "BACKGROUND_RED=[41m"
set "BACKGROUND_GREEN=[42m"
set "BACKGROUND_YELLOW=[43m"
set "BACKGROUND_BLUE=[44m"
set "BACKGROUND_MAGENTA=[45m"
set "BACKGROUND_CYAN=[46m"
set "BACKGROUND_WHITE=[47m"

:: Text Bright Color
set "TEXT_BRIGHT_BLACK=[90m"
set "TEXT_BRIGHT_RED=[91m"
set "TEXT_BRIGHT_GREEN=[92m"
set "TEXT_BRIGHT_YELLOW=[93m"
set "TEXT_BRIGHT_BLUE=[94m"
set "TEXT_BRIGHT_MAGENTA=[95m"
set "TEXT_BRIGHT_CYAN=[96m"
set "TEXT_BRIGHT_WHITE=[97m"

:: Background Bright Color
set "BACKGROUND_BRIGHT_BLACK=[100m"
set "BACKGROUND_BRIGHT_RED=[101m"
set "BACKGROUND_BRIGHT_GREEN=[102m"
set "BACKGROUND_BRIGHT_YELLOW=[103m"
set "BACKGROUND_BRIGHT_BLUE=[104m"
set "BACKGROUND_BRIGHT_MAGENTA=[105m"
set "BACKGROUND_BRIGHT_CYAN=[106m"
set "BACKGROUND_BRIGHT_WHITE=[107m"

:: Style Type
set "RESET_STYLE=[0m"
set "BOLD_STYLE=[1m"
set "ITALIC_STYLE=[3m"
set "UNDERLINE_STYLE=[4m"