@echo off

:: Prompt Theme
prompt $E%TEXT_YELLOW%$C$E%TEXT_BRIGHT_GREEN%$D$E%TEXT_YELLOW%$F$E%RESET_STYLE%$E%BOLD_STYLE%:$E%RESET_STYLE%$E%TEXT_YELLOW%$C$E%TEXT_BRIGHT_BLUE%$P$E%TEXT_YELLOW%$F$E%TEXT_BRIGHT_CYAN%$_$$$E%RESET_STYLE%$S