@echo off

:: Prompt Theme
prompt $E%TEXT_BRIGHT_BLACK%$E%BACKGROUND_BRIGHT_BLUE%$E%TEXT_BLACK%  $E%BACKGROUND_BRIGHT_CYAN%  cmd $E%TEXT_BRIGHT_BLACK%$E%BACKGROUND_BLACK%$_$E%TEXT_YELLOW%┌──❮$E%TEXT_BRIGHT_GREEN%  $T $E%TEXT_YELLOW%❯─❮$E%TEXT_BRIGHT_GREEN%  $D $E%TEXT_YELLOW%❯─❮  $E%TEXT_BRIGHT_CYAN%"$P" $E%TEXT_YELLOW%❯$_└─$E%TEXT_BRIGHT_BLUE%$E%RESET_STYLE%$S