@echo off

:: Prompt Theme
prompt $E%TEXT_YELLOW%$E%BACKGROUND_BRIGHT_BLUE%$E%TEXT_BLACK%   cmd $E%TEXT_YELLOW%$E%BACKGROUND_BRIGHT_CYAN%$E%TEXT_BLACK%  $P $E%TEXT_YELLOW%$E%BACKGROUND_BLACK%$_$E%TEXT_GREEN%$E%RESET_STYLE%$S